// ワンダせんせいの なぞとき たんていじむしょ — 問題のデータ（もと）
//
// 書き方
// - 漢字は {漢字|よみ} と書きます（1年生で習う漢字だけ）。
// - 分かち書きは、半角スペースで区切ります。
// - itsu / doko / dare / nani は答えです。文章の中に、そのままの形で入っています（ヒントの色の線に使います）。
// - ask：ステージ1〜4で聞く手がかり（1つだけ）。ステージ5からは4つとも聞きます。
// - q：2文・3文の文章で使う、くわしい問いかけ。ない手がかりは、ふつうの問いかけになります。
// - ng：レベル1の、まちがいやすい選択肢（足りない分は自動で選びます）。
// - k：レベル2の入力。a＝打つ字、f＝わく（＿のところに □ を出します）。
// - pic：挿絵の説明（先生用）、en：Canva で挿絵を作るときのことば。
//
// id は記録と結びつくので、あとから変えないでください。

const L1 = [
  // ── ステージ1：だれが（1文）
  { id: '1-01', st: 1, ask: 'dare', t: ['あさ、ゆうとくんは こうえんで ボールを けりました。'],
    itsu: 'あさ', doko: 'こうえん', dare: 'ゆうとくん', nani: 'ボールを けりました',
    pic: 'あさの こうえんで、男の子が ボールを けっている', en: 'In the morning, a boy kicks a soccer ball in a park' },
  { id: '1-02', st: 1, ask: 'dare', t: ['ひるに、{犬|いぬ}が にわで ほねを かじりました。'],
    itsu: 'ひる', doko: 'にわ', dare: '{犬|いぬ}', nani: 'ほねを かじりました',
    pic: 'ひるの にわで、犬が ほねを かじっている', en: 'At noon, a dog chews a bone in a sunny backyard garden' },
  { id: '1-03', st: 1, ask: 'dare', t: ['よる、おかあさんは だいどころで カレーを つくりました。'],
    itsu: 'よる', doko: 'だいどころ', dare: 'おかあさん', nani: 'カレーを つくりました',
    pic: 'よるの だいどころで、おかあさんが カレーを つくっている', en: 'In the evening, a mother cooks curry in a pot in a kitchen, dark window' },
  { id: '1-04', st: 1, ask: 'dare', t: ['きのう、さくらさんは としょしつで {本|ほん}を よみました。'],
    itsu: 'きのう', doko: 'としょしつ', dare: 'さくらさん', nani: '{本|ほん}を よみました',
    pic: 'としょしつで、女の子が 本を よんでいる', en: 'A girl reads a book in a school library with bookshelves' },
  { id: '1-05', st: 1, ask: 'dare', t: ['{日|にち}ようび、おじいちゃんは はたけで いもを ほりました。'],
    itsu: '{日|にち}ようび', doko: 'はたけ', dare: 'おじいちゃん', nani: 'いもを ほりました',
    pic: 'はたけで、おじいちゃんが さつまいもを ほっている', en: 'A grandfather digs up sweet potatoes in a vegetable field' },

  // ── ステージ2：どこで（1文）
  { id: '1-06', st: 2, ask: 'doko', t: ['ひるに、ねこが にわで ひなたぼっこを しました。'],
    itsu: 'ひる', doko: 'にわ', dare: 'ねこ', nani: 'ひなたぼっこを しました',
    pic: 'ひるの にわで、ねこが ひなたぼっこを している', en: 'At noon, a cat relaxes and sunbathes in a garden' },
  { id: '1-07', st: 2, ask: 'doko', t: ['{夕|ゆう}がた、はるとくんは {川|かわ}で さかなを つりました。'],
    itsu: '{夕|ゆう}がた', doko: '{川|かわ}', dare: 'はるとくん', nani: 'さかなを つりました',
    pic: 'ゆうがたの 川で、男の子が さかなを つっている', en: 'At sunset, a boy catches a fish with a fishing rod at a river' },
  { id: '1-08', st: 2, ask: 'doko', t: ['きのう、みおさんは プールで およぎました。'],
    itsu: 'きのう', doko: 'プール', dare: 'みおさん', nani: 'およぎました',
    pic: 'プールで、女の子が およいでいる', en: 'A girl swims in a swimming pool' },
  { id: '1-09', st: 2, ask: 'doko', t: ['あさ、{先生|せんせい}は きょうしつで うたを うたいました。'],
    itsu: 'あさ', doko: 'きょうしつ', dare: '{先生|せんせい}', nani: 'うたを うたいました',
    pic: 'きょうしつで、先生が うたを うたっている', en: 'In the morning, a teacher sings a song in a classroom' },
  { id: '1-10', st: 2, ask: 'doko', t: ['{日|にち}ようび、ゆいさんは スーパーで にんじんを かいました。'],
    itsu: '{日|にち}ようび', doko: 'スーパー', dare: 'ゆいさん', nani: 'にんじんを かいました',
    pic: 'スーパーで、女の子が にんじんを かっている', en: 'A girl buys carrots at a supermarket' },

  // ── ステージ3：いつ（1文）
  { id: '1-11', st: 3, ask: 'itsu', t: ['あさ、そうたくんは げんかんで くつを はきました。'],
    itsu: 'あさ', doko: 'げんかん', dare: 'そうたくん', nani: 'くつを はきました',
    pic: 'あさの げんかんで、男の子が くつを はいている', en: 'In the morning, a boy puts on his shoes at the entrance of a house, morning sun' },
  { id: '1-12', st: 3, ask: 'itsu', t: ['よる、おとうさんは おふろで せなかを あらいました。'],
    itsu: 'よる', doko: 'おふろ', dare: 'おとうさん', nani: 'せなかを あらいました',
    pic: 'よるの おふろで、おとうさんが せなかを あらっている', en: 'At night, a father washes his back with a towel in a bathroom, bubbles' },
  { id: '1-13', st: 3, ask: 'itsu', t: ['なつ{休|やす}みに、けんたくんは うみで かいを ひろいました。'],
    itsu: 'なつ{休|やす}み', doko: 'うみ', dare: 'けんたくん', nani: 'かいを ひろいました',
    pic: 'なつの うみで、男の子が かいがらを ひろっている', en: 'In summer, a boy picks up seashells on a beach' },
  { id: '1-14', st: 3, ask: 'itsu', t: ['{雨|あめ}の {日|ひ}に、かえるが いけで ケロケロと なきました。'],
    itsu: '{雨|あめ}の {日|ひ}', doko: 'いけ', dare: 'かえる', nani: 'ケロケロと なきました',
    pic: 'あめの いけで、かえるが ないている', en: 'On a rainy day, a green frog croaks on a lily pad in a pond, raindrops' },
  { id: '1-15', st: 3, ask: 'itsu', t: ['クリスマスに、あおいさんは いえで ケーキを たべました。'],
    itsu: 'クリスマス', doko: 'いえ', dare: 'あおいさん', nani: 'ケーキを たべました',
    pic: 'クリスマスに、女の子が いえで ケーキを たべている', en: 'At Christmas, a girl eats a strawberry cake at home, Christmas tree' },

  // ── ステージ4：なにを した（1文）
  { id: '1-16', st: 4, ask: 'nani', t: ['あさ、ひなたさんは にわで {花|はな}に {水|みず}を やりました。'],
    itsu: 'あさ', doko: 'にわ', dare: 'ひなたさん', nani: '{花|はな}に {水|みず}を やりました',
    ng: { nani: ['{花|はな}を つみました', 'にわを はしりました'] },
    pic: 'あさの にわで、女の子が 花に 水を やっている', en: 'In the morning, a girl waters flowers with a watering can in a garden' },
  { id: '1-17', st: 4, ask: 'nani', t: ['{休|やす}みじかんに、りくくんは うんどうじょうで なわとびを しました。'],
    itsu: '{休|やす}みじかん', doko: 'うんどうじょう', dare: 'りくくん', nani: 'なわとびを しました',
    ng: { nani: ['てつぼうを しました', 'ボールを なげました'] },
    pic: 'がっこうの うんどうじょうで、男の子が なわとびを している', en: 'A boy jumps rope on a school playground' },
  { id: '1-18', st: 4, ask: 'nani', t: ['きのう、おばあちゃんは へやで セーターを あみました。'],
    itsu: 'きのう', doko: 'へや', dare: 'おばあちゃん', nani: 'セーターを あみました',
    ng: { nani: ['セーターを きました', 'おちゃを のみました'] },
    pic: 'へやで、おばあちゃんが セーターを あんでいる', en: 'A grandmother knits a sweater with yarn in a cozy room' },
  { id: '1-19', st: 4, ask: 'nani', t: ['ひるに、パンダが どうぶつえんで ささを たべました。'],
    itsu: 'ひる', doko: 'どうぶつえん', dare: 'パンダ', nani: 'ささを たべました',
    ng: { nani: ['ささを あつめました', 'ひるねを しました'] },
    pic: 'どうぶつえんで、パンダが ささを たべている', en: 'A panda eats bamboo leaves at a zoo' },
  { id: '1-20', st: 4, ask: 'nani', t: ['{夕|ゆう}がた、こはるさんは こうえんで ブランコに のりました。'],
    itsu: '{夕|ゆう}がた', doko: 'こうえん', dare: 'こはるさん', nani: 'ブランコに のりました',
    ng: { nani: ['すべりだいで すべりました', 'ブランコを おしました'] },
    pic: 'ゆうがたの こうえんで、女の子が ブランコに のっている', en: 'At sunset, a girl rides a swing in a park' },

  // ── ステージ5：4つとも（1文）
  { id: '1-21', st: 5, t: ['あさ、だいちくんは うんどうじょうで はしりました。'],
    itsu: 'あさ', doko: 'うんどうじょう', dare: 'だいちくん', nani: 'はしりました',
    ng: { nani: ['あるきました', 'ねむりました'] },
    pic: 'あさの うんどうじょうで、男の子が はしっている', en: 'In the morning, a boy runs on a school sports ground' },
  { id: '1-22', st: 5, t: ['よる、うさぎが にわで {月|つき}を みました。'],
    itsu: 'よる', doko: 'にわ', dare: 'うさぎ', nani: '{月|つき}を みました',
    ng: { nani: ['ほしを かぞえました', 'にんじんを たべました'] },
    pic: 'よるの にわで、うさぎが まるい 月を みている', en: 'At night, a white rabbit looks up at the full moon in a garden' },
  { id: '1-23', st: 5, t: ['{日|にち}ようび、おとうさんは いえの まえで {車|くるま}を あらいました。'],
    itsu: '{日|にち}ようび', doko: 'いえの まえ', dare: 'おとうさん', nani: '{車|くるま}を あらいました',
    ng: { nani: ['{車|くるま}に のりました', '{車|くるま}を かいました'], doko: ['いえの なか', 'えきの まえ'] },
    pic: 'いえの まえで、おとうさんが 車を あらっている', en: 'A father washes a car with a sponge in front of a house' },
  { id: '1-24', st: 5, t: ['きのう、ゆいさんは パンやで メロンパンを かいました。'],
    itsu: 'きのう', doko: 'パンや', dare: 'ゆいさん', nani: 'メロンパンを かいました',
    ng: { nani: ['メロンパンを つくりました', 'メロンを かいました'] },
    pic: 'パンやさんで、女の子が メロンパンを かっている', en: 'A girl buys a melon bread bun at a bakery' },
  { id: '1-25', st: 5, t: ['ふゆ{休|やす}みに、はるとくんは {山|やま}で スキーを しました。'],
    itsu: 'ふゆ{休|やす}み', doko: '{山|やま}', dare: 'はるとくん', nani: 'スキーを しました',
    ng: { nani: ['ゆきだるまを つくりました', '{山|やま}に のぼりました'] },
    pic: 'ふゆの 雪山で、男の子が スキーを している', en: 'In winter, a boy skis down a snowy mountain' },

  // ── ステージ6：4つとも（1文・ならびかえ）
  { id: '1-26', st: 6, t: ['さくらさんは、あさ、にわで ちょうちょを みつけました。'],
    itsu: 'あさ', doko: 'にわ', dare: 'さくらさん', nani: 'ちょうちょを みつけました',
    ng: { nani: ['ちょうちょを つかまえました', '{花|はな}を みつけました'] },
    pic: 'あさの にわで、女の子が ちょうちょを みつけている', en: 'In the morning, a girl finds a butterfly on flowers in a garden' },
  { id: '1-27', st: 6, t: ['ゆうとくんは、きのう、えきで おばあちゃんを まちました。'],
    itsu: 'きのう', doko: 'えき', dare: 'ゆうとくん', nani: 'おばあちゃんを まちました',
    ng: { dare: ['おばあちゃん'], nani: ['でんしゃに のりました', 'おばあちゃんに あいました'] },
    pic: 'えきで、男の子が おばあちゃんを まっている', en: 'A boy waits for his grandmother at a train station platform' },
  { id: '1-28', st: 6, t: ['ひるに、たいいくかんで そうたくんが ドッジボールを しました。'],
    itsu: 'ひる', doko: 'たいいくかん', dare: 'そうたくん', nani: 'ドッジボールを しました',
    ng: { nani: ['サッカーを しました', 'ボールを ひろいました'] },
    pic: 'たいいくかんで、男の子が ドッジボールを している', en: 'A boy plays dodgeball in a school gymnasium' },
  { id: '1-29', st: 6, t: ['くまは、あきに {森|もり}で どんぐりを あつめました。'],
    itsu: 'あき', doko: '{森|もり}', dare: 'くま', nani: 'どんぐりを あつめました',
    ng: { nani: ['どんぐりを うえました', 'はっぱを あつめました'] },
    pic: 'あきの 森で、くまが どんぐりを あつめている', en: 'In autumn, a brown bear gathers acorns in a forest with red and yellow leaves' },
  { id: '1-30', st: 6, t: ['えんそくの {日|ひ}に、こどもたちは {山|やま}の うえで おべんとうを たべました。'],
    itsu: 'えんそくの {日|ひ}', doko: '{山|やま}の うえ', dare: 'こどもたち', nani: 'おべんとうを たべました',
    ng: { doko: ['{山|やま}の した', '{川|かわ}の そば'], dare: ['{先生|せんせい}'], nani: ['おべんとうを つくりました', '{山|やま}を おりました'] },
    pic: '山の うえで、こどもたちが おべんとうを たべている', en: 'On a school field trip, children eat boxed lunches on top of a mountain' },

  // ── ステージ7：2文
  { id: '1-31', st: 7, t: ['{日|にち}ようびの あさの ことです。', 'ゆうとくんは こうえんで たこを あげました。'],
    itsu: '{日|にち}ようびの あさ', doko: 'こうえん', dare: 'ゆうとくん', nani: 'たこを あげました',
    ng: { itsu: ['{日|にち}ようびの よる', '{土|ど}ようびの あさ'], nani: ['ボールを なげました', 'たこを つくりました'] },
    pic: 'こうえんで、男の子が たこあげを している', en: 'A boy flies a kite in a park on a sunny morning' },
  { id: '1-32', st: 7, t: ['きのう、ゆいさんは としょしつで えほんを よみました。', 'とても おもしろかったです。'],
    itsu: 'きのう', doko: 'としょしつ', dare: 'ゆいさん', nani: 'えほんを よみました',
    ng: { nani: ['えほんを かいました', 'えを かきました'] },
    pic: 'としょしつで、女の子が えほんを よんで わらっている', en: 'A girl reads a picture book and smiles in a school library' },
  { id: '1-33', st: 7, t: ['なつの よるでした。', 'けんたくんは にわで はなびを しました。'],
    itsu: 'なつの よる', doko: 'にわ', dare: 'けんたくん', nani: 'はなびを しました',
    ng: { itsu: ['なつの あさ', 'ふゆの よる'], nani: ['すいかを たべました', 'ほしを みました'] },
    pic: 'なつの よるの にわで、男の子が はなびを している', en: 'On a summer night, a boy holds a sparkler firework in a garden' },
  { id: '1-34', st: 7, t: ['ひるに、ペンギンが いけで さかなを たべました。', 'おなかが いっぱいに なりました。'],
    itsu: 'ひる', doko: 'いけ', dare: 'ペンギン', nani: 'さかなを たべました',
    ng: { nani: ['さかなを つりました', 'いけで およぎました'] },
    pic: 'いけで、ペンギンが さかなを たべている', en: 'A penguin eats a fish by a pool of water' },
  { id: '1-35', st: 7, t: ['あきの ことです。', 'ひなたさんは {山|やま}で くりを ひろいました。'],
    itsu: 'あき', doko: '{山|やま}', dare: 'ひなたさん', nani: 'くりを ひろいました',
    ng: { nani: ['くりを たべました', 'はっぱを ひろいました'] },
    pic: 'あきの 山で、女の子が くりを ひろっている', en: 'In autumn, a girl picks up chestnuts on a mountain path' },

  // ── ステージ8：2文（まちがいやすい ことばが 2つ）
  { id: '1-36', st: 8, t: ['あさ、そうたくんは いえで ごはんを たべました。', 'ひるに、こうえんで サッカーを しました。'],
    itsu: 'ひる', doko: 'こうえん', dare: 'そうたくん', nani: 'サッカーを しました',
    q: { itsu: 'いつ サッカーを しましたか？', doko: 'どこで サッカーを しましたか？', dare: 'だれが サッカーを しましたか？', nani: 'そうたくんは こうえんで なにを しましたか？' },
    ng: { itsu: ['あさ'], doko: ['いえ'], nani: ['ごはんを たべました'] },
    pic: 'こうえんで、男の子が サッカーを している', en: 'A boy plays soccer in a park at noon' },
  { id: '1-37', st: 8, t: ['{夕|ゆう}がた、はるとくんは {犬|いぬ}と さんぽに いきました。', '{川|かわ}の そばで、{犬|いぬ}が ボールを おいかけました。'],
    itsu: '{夕|ゆう}がた', doko: '{川|かわ}の そば', dare: '{犬|いぬ}', nani: 'ボールを おいかけました',
    q: { itsu: 'いつの ことですか？', doko: 'どこで ボールを おいかけましたか？', dare: 'だれが ボールを おいかけましたか？', nani: '{犬|いぬ}は {川|かわ}の そばで なにを しましたか？' },
    ng: { dare: ['はるとくん'], doko: ['{川|かわ}の なか', 'いえの まえ'], nani: ['さんぽに いきました'] },
    pic: 'ゆうがたの 川の そばで、犬が ボールを おいかけている', en: 'At sunset, a dog chases a ball by a river while a boy watches' },
  { id: '1-38', st: 8, t: ['ふゆの あさ、ゆきが たくさん つもりました。', 'あおいさんは にわで ゆきだるまを つくりました。'],
    itsu: 'ふゆの あさ', doko: 'にわ', dare: 'あおいさん', nani: 'ゆきだるまを つくりました',
    q: { itsu: 'いつの ことですか？', doko: 'どこで ゆきだるまを つくりましたか？', dare: 'だれが ゆきだるまを つくりましたか？', nani: 'あおいさんは にわで なにを しましたか？' },
    ng: { itsu: ['ふゆの よる', 'なつの あさ'], dare: ['ゆき'], nani: ['ゆきが つもりました', 'ゆきがっせんを しました'] },
    pic: 'ゆきの つもった にわで、女の子が ゆきだるまを つくっている', en: 'On a winter morning, a girl makes a snowman in a snowy garden' },
  { id: '1-39', st: 8, t: ['{月|げつ}ようびに、りくくんは かぜを ひきました。', '{火|か}ようびに、びょういんへ いきました。'],
    itsu: '{火|か}ようび', doko: 'びょういん', dare: 'りくくん', nani: 'かぜを ひきました',
    q: { itsu: 'いつ びょういんへ いきましたか？', doko: 'りくくんは {火|か}ようびに どこへ いきましたか？', dare: 'だれが かぜを ひきましたか？', nani: 'りくくんは {月|げつ}ようびに どう なりましたか？' },
    ng: { itsu: ['{月|げつ}ようび'], doko: ['{学校|がっこう}'], nani: ['びょういんへ いきました', 'くすりを のみました'] },
    pic: 'びょういんで、マスクを した 男の子が おいしゃさんに みてもらっている', en: 'A boy wearing a face mask sees a doctor at a hospital' },
  { id: '1-40', st: 8, t: ['{日|にち}ようびに、おとうさんは いえの まえで {車|くるま}を あらいました。', 'そのあと、ゆうとくんが {車|くるま}を ふきました。'],
    itsu: '{日|にち}ようび', doko: 'いえの まえ', dare: 'ゆうとくん', nani: '{車|くるま}を ふきました',
    q: { itsu: 'いつの ことですか？', doko: 'どこで {車|くるま}を あらいましたか？', dare: 'だれが {車|くるま}を ふきましたか？', nani: 'ゆうとくんは なにを しましたか？' },
    ng: { dare: ['おとうさん'], doko: ['いえの なか', 'えきの まえ'], nani: ['{車|くるま}を あらいました', '{車|くるま}に のりました'] },
    pic: 'いえの まえで、男の子が タオルで 車を ふいている。よこに おとうさん', en: 'A boy wipes a car with a towel in front of a house, his father holding a hose nearby' },

  // ── ステージ9：3文
  { id: '1-41', st: 9, t: ['うんどうかいの {日|ひ}の ことです。', 'ゆいさんは うんどうじょうで かけっこを しました。', 'いちばんに なって、うれしかったです。'],
    itsu: 'うんどうかいの {日|ひ}', doko: 'うんどうじょう', dare: 'ゆいさん', nani: 'かけっこを しました',
    ng: { itsu: ['えんそくの {日|ひ}', 'たんじょうび'], nani: ['たまいれを しました', 'おうえんを しました'] },
    pic: 'うんどうかいで、女の子が かけっこで 1ばんに なっている', en: 'At a school sports day, a girl wins a footrace and crosses the finish tape' },
  { id: '1-42', st: 9, t: ['あさ、みおさんは はやく おきました。', 'にわに でて、あさがおに {水|みず}を やりました。', 'あおい {花|はな}が さいて いました。'],
    itsu: 'あさ', doko: 'にわ', dare: 'みおさん', nani: 'あさがおに {水|みず}を やりました',
    q: { itsu: 'いつの ことですか？', doko: 'どこで あさがおに {水|みず}を やりましたか？', dare: 'だれが あさがおに {水|みず}を やりましたか？', nani: 'みおさんは にわで なにを しましたか？' },
    ng: { nani: ['はやく おきました', 'あさがおを つみました'] },
    pic: 'あさの にわで、女の子が あおい あさがおに 水を やっている', en: 'In the morning, a girl waters blue morning glory flowers in a garden' },
  { id: '1-43', st: 9, t: ['ひるの ことです。', 'ぞうが いけの なかに はいりました。', 'はなで {水|みず}を かけて、からだを あらいました。'],
    itsu: 'ひる', doko: 'いけ', dare: 'ぞう', nani: 'からだを あらいました',
    q: { itsu: 'いつの ことですか？', doko: 'どこに はいりましたか？', dare: 'だれが いけに はいりましたか？', nani: 'ぞうは はなで {水|みず}を かけて、なにを しましたか？' },
    ng: { nani: ['{水|みず}を のみました', 'いけで およぎました'] },
    pic: 'いけの なかで、ぞうが はなで 水を かけている', en: 'An elephant sprays water on itself with its trunk in a pond' },
  { id: '1-44', st: 9, t: ['えんそくの {日|ひ}です。', 'だいちくんたちは {山|やま}に のぼりました。', '{山|やま}の うえで、みんなで おべんとうを たべました。'],
    itsu: 'えんそくの {日|ひ}', doko: '{山|やま}の うえ', dare: 'だいちくんたち', nani: 'おべんとうを たべました',
    q: { itsu: 'いつの ことですか？', doko: 'どこで おべんとうを たべましたか？', dare: 'だれが {山|やま}に のぼりましたか？', nani: 'みんなは {山|やま}の うえで なにを しましたか？' },
    ng: { itsu: ['うんどうかいの {日|ひ}', '{雨|あめ}の {日|ひ}'], doko: ['{山|やま}の した', '{川|かわ}の そば'], dare: ['{先生|せんせい}', 'おとうさんたち'], nani: ['{山|やま}に のぼりました', 'おべんとうを つくりました'] },
    pic: '山の うえで、こどもたちが おべんとうを ひろげている', en: 'Children on a hike eat lunch together on a mountaintop with a view' },
  { id: '1-45', st: 9, t: ['おしょうがつの ことです。', 'こはるさんは おじいちゃんの いえに いきました。', 'ちかくの こうえんで、たこあげを しました。'],
    itsu: 'おしょうがつ', doko: 'こうえん', dare: 'こはるさん', nani: 'たこあげを しました',
    q: { itsu: 'いつの ことですか？', doko: 'どこで たこあげを しましたか？', dare: 'だれが おじいちゃんの いえに いきましたか？', nani: 'こはるさんは こうえんで なにを しましたか？' },
    ng: { itsu: ['クリスマス', 'たんじょうび'], doko: ['おじいちゃんの いえ'], dare: ['おじいちゃん'], nani: ['おじいちゃんの いえに いきました', 'こまを まわしました'] },
    pic: 'おしょうがつに、女の子が こうえんで たこあげを している', en: 'At New Year, a girl flies a traditional Japanese kite in a park with her grandfather' },

  // ── ステージ10：3文（まちがいやすい ことばが いくつも）
  { id: '1-46', st: 10, t: ['{日|にち}ようびの あさ、ゆうとくんは でんしゃに のりました。', 'ひるに、うみで すなの しろを つくりました。', '{夕|ゆう}がた、いえに かえりました。'],
    itsu: 'ひる', doko: 'うみ', dare: 'ゆうとくん', nani: 'すなの しろを つくりました',
    q: { itsu: 'いつ すなの しろを つくりましたか？', doko: 'どこで すなの しろを つくりましたか？', dare: 'だれが でんしゃに のりましたか？', nani: 'ゆうとくんは ひるに なにを しましたか？' },
    ng: { itsu: ['{日|にち}ようびの あさ', '{夕|ゆう}がた'], doko: ['いえ', 'えき'], nani: ['でんしゃに のりました', 'いえに かえりました'] },
    pic: 'うみの すなはまで、男の子が すなの おしろを つくっている', en: 'A boy builds a sandcastle on a sunny beach' },
  { id: '1-47', st: 10, t: ['きのう、さくらさんと ゆいさんは こうえんで あそびました。', 'さくらさんは ブランコに のりました。', 'ゆいさんは すべりだいで すべりました。'],
    itsu: 'きのう', doko: 'こうえん', dare: 'ゆいさん', nani: 'ブランコに のりました',
    q: { itsu: 'いつの ことですか？', doko: 'ふたりは どこで あそびましたか？', dare: 'だれが すべりだいで すべりましたか？', nani: 'さくらさんは なにを しましたか？' },
    ng: { dare: ['さくらさん'], nani: ['すべりだいで すべりました', 'すなばで あそびました'] },
    pic: 'こうえんで、女の子が ブランコに のり、もう 1人の 女の子が すべりだいを すべっている', en: 'Two girls play in a park: one on a swing, the other going down a slide' },
  { id: '1-48', st: 10, t: ['あさ、ねこの ミケは へやで ねて いました。', 'ひるに なると、にわへ でて いきました。', 'にわで、ちょうちょを おいかけました。'],
    itsu: 'ひる', doko: 'にわ', dare: 'ミケ', nani: 'ちょうちょを おいかけました',
    q: { itsu: 'いつ にわへ でて いきましたか？', doko: 'どこで ちょうちょを おいかけましたか？', dare: 'だれが ちょうちょを おいかけましたか？', nani: 'ミケは にわで なにを しましたか？' },
    ng: { itsu: ['あさ'], doko: ['へや'], dare: ['ちょうちょ', 'ポチ', 'うさぎ'], nani: ['へやで ねて いました', 'ちょうちょに おいかけられました'] },
    pic: 'にわで、みけねこが ちょうちょを おいかけている', en: 'A calico cat chases a butterfly in a sunny garden' },
  { id: '1-49', st: 10, t: ['{月|げつ}ようびに、{先生|せんせい}が あさがおの たねを くばりました。', '{火|か}ようびに、こどもたちは はたけに たねを まきました。', '{水|すい}ようびに、みんなで {水|みず}を やりました。'],
    itsu: '{火|か}ようび', doko: 'はたけ', dare: '{先生|せんせい}', nani: 'たねを まきました',
    q: { itsu: 'いつ たねを まきましたか？', doko: 'どこに たねを まきましたか？', dare: 'だれが たねを くばりましたか？', nani: 'こどもたちは {火|か}ようびに なにを しましたか？' },
    ng: { itsu: ['{月|げつ}ようび', '{水|すい}ようび'], dare: ['こどもたち'], doko: ['きょうしつ'], nani: ['たねを くばりました', '{水|みず}を やりました'] },
    pic: 'がっこうの はたけで、こどもたちが あさがおの たねを まいている', en: 'Elementary school children plant seeds in a school garden plot with their teacher' },
  { id: '1-50', st: 10, t: ['クリスマスの よる、ひなたさんは はやく ねました。', 'つぎの {日|ひ}の あさ、まくらの そばに プレゼントが ありました。', 'ひなたさんは うれしくて、{大|おお}きな こえを だしました。'],
    itsu: 'クリスマスの よる', doko: 'まくらの そば', dare: 'ひなたさん', nani: '{大|おお}きな こえを だしました',
    q: { itsu: 'いつ はやく ねましたか？', doko: 'プレゼントは どこに ありましたか？', dare: 'だれが はやく ねましたか？', nani: 'ひなたさんは うれしくて、なにを しましたか？' },
    ng: { itsu: ['つぎの {日|ひ}の あさ', 'たんじょうびの よる'], doko: ['ツリーの した', 'げんかん'], nani: ['はやく ねました', 'プレゼントを かいました'] },
    pic: 'あさ、女の子が まくらの そばの プレゼントを みつけて よろこんでいる', en: 'On Christmas morning, a happy girl finds a wrapped present next to her pillow in bed' },
];

const L2 = [
  // ── ステージ1：だれが
  { id: '2-01', st: 1, ask: 'dare', t: ['あさ、たろうくんは こうえんで はしりました。'],
    itsu: 'あさ', doko: 'こうえん', dare: 'たろうくん', nani: 'はしりました',
    k: { itsu: { a: 'あさ', f: '＿' }, doko: { a: 'こうえん', f: '＿' }, dare: { a: 'たろう', f: '＿くん' }, nani: { a: 'はしり', f: '＿ました' } },
    pic: 'あさの こうえんで、男の子が はしっている', en: 'In the morning, a boy runs in a park' },
  { id: '2-02', st: 1, ask: 'dare', t: ['ひるに、ねこが にわで ねました。'],
    itsu: 'ひる', doko: 'にわ', dare: 'ねこ', nani: 'ねました',
    k: { itsu: { a: 'ひる', f: '＿' }, doko: { a: 'にわ', f: '＿' }, dare: { a: 'ねこ', f: '＿' }, nani: { a: 'ね', f: '＿ました' } },
    pic: 'ひるの にわで、ねこが まるくなって ねている', en: 'At noon, a cat sleeps curled up in a sunny garden' },
  { id: '2-03', st: 1, ask: 'dare', t: ['よる、パンダが どうぶつえんで ねむりました。'],
    itsu: 'よる', doko: 'どうぶつえん', dare: 'パンダ', nani: 'ねむりました',
    k: { itsu: { a: 'よる', f: '＿' }, doko: { a: 'どうぶつえん', f: '＿' }, dare: { a: 'パンダ', f: '＿' }, nani: { a: 'ねむり', f: '＿ました' } },
    pic: 'よるの どうぶつえんで、パンダが ねむっている', en: 'At night, a panda sleeps at a zoo under the moon' },
  { id: '2-04', st: 1, ask: 'dare', t: ['きのう、まいさんは いえで えを かきました。'],
    itsu: 'きのう', doko: 'いえ', dare: 'まいさん', nani: 'えを かきました',
    k: { itsu: { a: 'きのう', f: '＿' }, doko: { a: 'いえ', f: '＿' }, dare: { a: 'まい', f: '＿さん' }, nani: { a: 'かき', f: 'えを ＿ました' } },
    pic: 'いえで、女の子が クレヨンで えを かいている', en: 'A girl draws a picture with crayons at home' },
  { id: '2-05', st: 1, ask: 'dare', t: ['あさ、{先生|せんせい}は きょうしつで {本|ほん}を よみました。'],
    itsu: 'あさ', doko: 'きょうしつ', dare: '{先生|せんせい}', nani: '{本|ほん}を よみました',
    k: { itsu: { a: 'あさ', f: '＿' }, doko: { a: 'きょうしつ', f: '＿' }, dare: { a: 'せんせい', f: '＿' }, nani: { a: 'よみ', f: '{本|ほん}を ＿ました' } },
    pic: 'きょうしつで、先生が こどもたちに 本を よんでいる', en: 'In the morning, a teacher reads a picture book aloud to children in a classroom' },

  // ── ステージ2：どこで
  { id: '2-06', st: 2, ask: 'doko', t: ['あさ、さるが {山|やま}で きのみを たべました。'],
    itsu: 'あさ', doko: '{山|やま}', dare: 'さる', nani: 'きのみを たべました',
    k: { itsu: { a: 'あさ', f: '＿' }, doko: { a: 'やま', f: '＿' }, dare: { a: 'さる', f: '＿' }, nani: { a: 'たべ', f: 'きのみを ＿ました' } },
    pic: '山で、さるが きのみを たべている', en: 'A monkey eats berries on a green mountain in the morning' },
  { id: '2-07', st: 2, ask: 'doko', t: ['ひるに、こどもたちは プールで およぎました。'],
    itsu: 'ひる', doko: 'プール', dare: 'こどもたち', nani: 'およぎました',
    k: { itsu: { a: 'ひる', f: '＿' }, doko: { a: 'プール', f: '＿' }, dare: { a: 'こども', f: '＿たち' }, nani: { a: 'およぎ', f: '＿ました' } },
    pic: 'プールで、こどもたちが およいでいる', en: 'Children swim and splash in a swimming pool at noon' },
  { id: '2-08', st: 2, ask: 'doko', t: ['{夕|ゆう}がた、あやさんは うみで かいを ひろいました。'],
    itsu: '{夕|ゆう}がた', doko: 'うみ', dare: 'あやさん', nani: 'かいを ひろいました',
    k: { itsu: { a: 'ゆうがた', f: '＿' }, doko: { a: 'うみ', f: '＿' }, dare: { a: 'あや', f: '＿さん' }, nani: { a: 'ひろい', f: 'かいを ＿ました' } },
    pic: 'ゆうがたの うみで、女の子が かいを ひろっている', en: 'At sunset, a girl picks up seashells at the beach' },
  { id: '2-09', st: 2, ask: 'doko', t: ['よる、おとうさんは へやで {本|ほん}を よみました。'],
    itsu: 'よる', doko: 'へや', dare: 'おとうさん', nani: '{本|ほん}を よみました',
    k: { itsu: { a: 'よる', f: '＿' }, doko: { a: 'へや', f: '＿' }, dare: { a: 'おとうさん', f: '＿' }, nani: { a: 'よみ', f: '{本|ほん}を ＿ました' } },
    pic: 'よるの へやで、おとうさんが 本を よんでいる', en: 'At night, a father reads a book in a cozy living room with a lamp' },
  { id: '2-10', st: 2, ask: 'doko', t: ['きのう、ゆうきくんは スーパーで パンを かいました。'],
    itsu: 'きのう', doko: 'スーパー', dare: 'ゆうきくん', nani: 'パンを かいました',
    k: { itsu: { a: 'きのう', f: '＿' }, doko: { a: 'スーパー', f: '＿' }, dare: { a: 'ゆうき', f: '＿くん' }, nani: { a: 'かい', f: 'パンを ＿ました' } },
    pic: 'スーパーで、男の子が パンを かっている', en: 'A boy buys a loaf of bread at a supermarket' },

  // ── ステージ3：いつ
  { id: '2-11', st: 3, ask: 'itsu', t: ['あさ、りすが {森|もり}で どんぐりを ひろいました。'],
    itsu: 'あさ', doko: '{森|もり}', dare: 'りす', nani: 'どんぐりを ひろいました',
    k: { itsu: { a: 'あさ', f: '＿' }, doko: { a: 'もり', f: '＿' }, dare: { a: 'りす', f: '＿' }, nani: { a: 'ひろい', f: 'どんぐりを ＿ました' } },
    pic: 'あさの 森で、りすが どんぐりを ひろっている', en: 'In the morning, a squirrel picks up an acorn in a forest' },
  { id: '2-12', st: 3, ask: 'itsu', t: ['よる、ふくろうが {木|き}の うえで なきました。'],
    itsu: 'よる', doko: '{木|き}の うえ', dare: 'ふくろう', nani: 'なきました',
    k: { itsu: { a: 'よる', f: '＿' }, doko: { a: 'き', f: '＿の うえ' }, dare: { a: 'ふくろう', f: '＿' }, nani: { a: 'なき', f: '＿ました' } },
    pic: 'よる、木の えだの うえで、ふくろうが ないている', en: 'At night, an owl hoots on a tree branch under the moon and stars' },
  { id: '2-13', st: 3, ask: 'itsu', t: ['なつに、たくみくんは {川|かわ}で あそびました。'],
    itsu: 'なつ', doko: '{川|かわ}', dare: 'たくみくん', nani: 'あそびました',
    k: { itsu: { a: 'なつ', f: '＿' }, doko: { a: 'かわ', f: '＿' }, dare: { a: 'たくみ', f: '＿くん' }, nani: { a: 'あそび', f: '＿ました' } },
    pic: 'なつの 川で、男の子が 水あそびを している', en: 'In summer, a boy splashes and plays in a shallow river' },
  { id: '2-14', st: 3, ask: 'itsu', t: ['クリスマスに、りなさんは いえで ケーキを たべました。'],
    itsu: 'クリスマス', doko: 'いえ', dare: 'りなさん', nani: 'ケーキを たべました',
    k: { itsu: { a: 'クリスマス', f: '＿' }, doko: { a: 'いえ', f: '＿' }, dare: { a: 'りな', f: '＿さん' }, nani: { a: 'たべ', f: 'ケーキを ＿ました' } },
    pic: 'クリスマスに、女の子が いえで ケーキを たべている', en: 'At Christmas, a girl eats a slice of Christmas cake at home with decorations' },
  { id: '2-15', st: 3, ask: 'itsu', t: ['きのう、おかあさんは にわで {花|はな}を うえました。'],
    itsu: 'きのう', doko: 'にわ', dare: 'おかあさん', nani: '{花|はな}を うえました',
    k: { itsu: { a: 'きのう', f: '＿' }, doko: { a: 'にわ', f: '＿' }, dare: { a: 'おかあさん', f: '＿' }, nani: { a: 'うえ', f: '{花|はな}を ＿ました' } },
    pic: 'にわで、おかあさんが 花を うえている', en: 'A mother plants flowers in a garden with a small shovel' },

  // ── ステージ4：なにを した
  { id: '2-16', st: 4, ask: 'nani', t: ['あさ、こうたくんは にわで ボールを けりました。'],
    itsu: 'あさ', doko: 'にわ', dare: 'こうたくん', nani: 'ボールを けりました',
    k: { itsu: { a: 'あさ', f: '＿' }, doko: { a: 'にわ', f: '＿' }, dare: { a: 'こうた', f: '＿くん' }, nani: { a: 'けり', f: 'ボールを ＿ました' } },
    pic: 'あさの にわで、男の子が ボールを けっている', en: 'In the morning, a boy kicks a ball in a backyard' },
  { id: '2-17', st: 4, ask: 'nani', t: ['ひるに、うさぎが はたけで にんじんを たべました。'],
    itsu: 'ひる', doko: 'はたけ', dare: 'うさぎ', nani: 'にんじんを たべました',
    k: { itsu: { a: 'ひる', f: '＿' }, doko: { a: 'はたけ', f: '＿' }, dare: { a: 'うさぎ', f: '＿' }, nani: { a: 'たべ', f: 'にんじんを ＿ました' } },
    pic: 'はたけで、うさぎが にんじんを たべている', en: 'A rabbit eats a carrot in a vegetable field' },
  { id: '2-18', st: 4, ask: 'nani', t: ['{夕|ゆう}がた、ももさんは こうえんで うたを うたいました。'],
    itsu: '{夕|ゆう}がた', doko: 'こうえん', dare: 'ももさん', nani: 'うたを うたいました',
    k: { itsu: { a: 'ゆうがた', f: '＿' }, doko: { a: 'こうえん', f: '＿' }, dare: { a: 'もも', f: '＿さん' }, nani: { a: 'うたい', f: 'うたを ＿ました' } },
    pic: 'ゆうがたの こうえんで、女の子が うたを うたっている', en: 'At sunset, a girl sings happily in a park, music notes' },
  { id: '2-19', st: 4, ask: 'nani', t: ['よる、{犬|いぬ}が いえの まえで ほえました。'],
    itsu: 'よる', doko: 'いえの まえ', dare: '{犬|いぬ}', nani: 'ほえました',
    k: { itsu: { a: 'よる', f: '＿' }, doko: { a: 'いえ', f: '＿の まえ' }, dare: { a: 'いぬ', f: '＿' }, nani: { a: 'ほえ', f: '＿ました' } },
    pic: 'よる、いえの まえで、犬が ほえている', en: 'At night, a dog barks in front of a house' },
  { id: '2-20', st: 4, ask: 'nani', t: ['きのう、おじいちゃんは {川|かわ}で さかなを つりました。'],
    itsu: 'きのう', doko: '{川|かわ}', dare: 'おじいちゃん', nani: 'さかなを つりました',
    k: { itsu: { a: 'きのう', f: '＿' }, doko: { a: 'かわ', f: '＿' }, dare: { a: 'おじいちゃん', f: '＿' }, nani: { a: 'つり', f: 'さかなを ＿ました' } },
    pic: '川で、おじいちゃんが さかなを つっている', en: 'A grandfather catches a fish with a fishing rod at a river' },

  // ── ステージ5：4つとも
  { id: '2-21', st: 5, t: ['あさ、ゆなさんは こうえんで なわとびを しました。'],
    itsu: 'あさ', doko: 'こうえん', dare: 'ゆなさん', nani: 'なわとびを しました',
    k: { itsu: { a: 'あさ', f: '＿' }, doko: { a: 'こうえん', f: '＿' }, dare: { a: 'ゆな', f: '＿さん' }, nani: { a: 'なわとび', f: '＿を しました' } },
    pic: 'あさの こうえんで、女の子が なわとびを している', en: 'In the morning, a girl jumps rope in a park' },
  { id: '2-22', st: 5, t: ['ひるに、ライオンが どうぶつえんで にくを たべました。'],
    itsu: 'ひる', doko: 'どうぶつえん', dare: 'ライオン', nani: 'にくを たべました',
    k: { itsu: { a: 'ひる', f: '＿' }, doko: { a: 'どうぶつえん', f: '＿' }, dare: { a: 'ライオン', f: '＿' }, nani: { a: 'たべ', f: 'にくを ＿ました' } },
    pic: 'どうぶつえんで、ライオンが にくを たべている', en: 'A lion eats a piece of meat at a zoo' },
  { id: '2-23', st: 5, t: ['よる、ひろとくんは おふろで せなかを あらいました。'],
    itsu: 'よる', doko: 'おふろ', dare: 'ひろとくん', nani: 'せなかを あらいました',
    k: { itsu: { a: 'よる', f: '＿' }, doko: { a: 'おふろ', f: '＿' }, dare: { a: 'ひろと', f: '＿くん' }, nani: { a: 'あらい', f: 'せなかを ＿ました' } },
    pic: 'よるの おふろで、男の子が せなかを あらっている', en: 'At night, a boy washes his back in a bathtub with bubbles' },
  { id: '2-24', st: 5, t: ['あきに、くまが {森|もり}で どんぐりを あつめました。'],
    itsu: 'あき', doko: '{森|もり}', dare: 'くま', nani: 'どんぐりを あつめました',
    k: { itsu: { a: 'あき', f: '＿' }, doko: { a: 'もり', f: '＿' }, dare: { a: 'くま', f: '＿' }, nani: { a: 'あつめ', f: 'どんぐりを ＿ました' } },
    pic: 'あきの 森で、くまが どんぐりを あつめている', en: 'In autumn, a bear collects acorns in a basket in a colorful forest' },
  { id: '2-25', st: 5, t: ['あさ、ことりが にわで うたを うたいました。'],
    itsu: 'あさ', doko: 'にわ', dare: 'ことり', nani: 'うたを うたいました',
    k: { itsu: { a: 'あさ', f: '＿' }, doko: { a: 'にわ', f: '＿' }, dare: { a: 'ことり', f: '＿' }, nani: { a: 'うたい', f: 'うたを ＿ました' } },
    pic: 'あさの にわで、ことりが うたっている', en: 'In the morning, a little bird sings in a garden, music notes' },

  // ── ステージ6：4つとも（ならびかえ）
  { id: '2-26', st: 6, t: ['ゆうきくんは、あさ、えきで おばあちゃんに あいました。'],
    itsu: 'あさ', doko: 'えき', dare: 'ゆうきくん', nani: 'おばあちゃんに あいました',
    k: { itsu: { a: 'あさ', f: '＿' }, doko: { a: 'えき', f: '＿' }, dare: { a: 'ゆうき', f: '＿くん' }, nani: { a: 'あい', f: 'おばあちゃんに ＿ました' } },
    pic: 'えきで、男の子が おばあちゃんに あっている', en: 'A boy happily meets his grandmother at a train station' },
  { id: '2-27', st: 6, t: ['こうえんで、ひるに、こどもたちが おにごっこを しました。'],
    itsu: 'ひる', doko: 'こうえん', dare: 'こどもたち', nani: 'おにごっこを しました',
    k: { itsu: { a: 'ひる', f: '＿' }, doko: { a: 'こうえん', f: '＿' }, dare: { a: 'こども', f: '＿たち' }, nani: { a: 'おにごっこ', f: '＿を しました' } },
    pic: 'こうえんで、こどもたちが おにごっこを している', en: 'Children play tag and run around in a park' },
  { id: '2-28', st: 6, t: ['こぐまが、はるに {川|かわ}で {水|みず}を のみました。'],
    itsu: 'はる', doko: '{川|かわ}', dare: 'こぐま', nani: '{水|みず}を のみました',
    k: { itsu: { a: 'はる', f: '＿' }, doko: { a: 'かわ', f: '＿' }, dare: { a: 'こぐま', f: '＿' }, nani: { a: 'のみ', f: '{水|みず}を ＿ました' } },
    pic: 'はるの 川で、こぐまが 水を のんでいる', en: 'In spring, a bear cub drinks water from a river, cherry blossoms' },
  { id: '2-29', st: 6, t: ['{土|ど}ようびに、あやさんは デパートで くつを かいました。'],
    itsu: '{土|ど}ようび', doko: 'デパート', dare: 'あやさん', nani: 'くつを かいました',
    k: { itsu: { a: 'どようび', f: '＿' }, doko: { a: 'デパート', f: '＿' }, dare: { a: 'あや', f: '＿さん' }, nani: { a: 'かい', f: 'くつを ＿ました' } },
    pic: 'デパートで、女の子が あたらしい くつを かっている', en: 'A girl buys new shoes at a department store' },
  { id: '2-30', st: 6, t: ['ゆきの {日|ひ}に、ペンギンが こおりの うえで すべりました。'],
    itsu: 'ゆきの {日|ひ}', doko: 'こおりの うえ', dare: 'ペンギン', nani: 'すべりました',
    k: { itsu: { a: 'ゆき', f: '＿の ひ' }, doko: { a: 'こおり', f: '＿の うえ' }, dare: { a: 'ペンギン', f: '＿' }, nani: { a: 'すべり', f: '＿ました' } },
    pic: 'ゆきの 日に、ペンギンが こおりの うえを すべっている', en: 'On a snowy day, a penguin slides on its belly across ice' },

  // ── ステージ7：2文
  { id: '2-31', st: 7, t: ['なつの ことです。', 'はなさんは うみで およぎました。'],
    itsu: 'なつ', doko: 'うみ', dare: 'はなさん', nani: 'およぎました',
    k: { itsu: { a: 'なつ', f: '＿' }, doko: { a: 'うみ', f: '＿' }, dare: { a: 'はな', f: '＿さん' }, nani: { a: 'およぎ', f: '＿ました' } },
    pic: 'なつの うみで、女の子が およいでいる', en: 'In summer, a girl swims in the sea with a float ring' },
  { id: '2-32', st: 7, t: ['あさ、ゆうとくんは はやく おきました。', 'そして、にわで たいそうを しました。'],
    itsu: 'あさ', doko: 'にわ', dare: 'ゆうとくん', nani: 'たいそうを しました',
    q: { nani: 'ゆうとくんは にわで なにを しましたか？' },
    k: { itsu: { a: 'あさ', f: '＿' }, doko: { a: 'にわ', f: '＿' }, dare: { a: 'ゆうと', f: '＿くん' }, nani: { a: 'たいそう', f: '＿を しました' } },
    pic: 'あさの にわで、男の子が たいそうを している', en: 'In the morning, a boy does stretching exercises in a garden' },
  { id: '2-33', st: 7, t: ['ひるに なりました。', 'ぞうが いけで {水|みず}を あびました。'],
    itsu: 'ひる', doko: 'いけ', dare: 'ぞう', nani: '{水|みず}を あびました',
    k: { itsu: { a: 'ひる', f: '＿' }, doko: { a: 'いけ', f: '＿' }, dare: { a: 'ぞう', f: '＿' }, nani: { a: 'あび', f: '{水|みず}を ＿ました' } },
    pic: 'いけで、ぞうが 水を あびている', en: 'An elephant showers water over itself in a pond at noon' },
  { id: '2-34', st: 7, t: ['よるの ことです。', 'おかあさんは だいどころで カレーを つくりました。'],
    itsu: 'よる', doko: 'だいどころ', dare: 'おかあさん', nani: 'カレーを つくりました',
    q: { nani: 'おかあさんは なにを つくりましたか？' },
    k: { itsu: { a: 'よる', f: '＿' }, doko: { a: 'だいどころ', f: '＿' }, dare: { a: 'おかあさん', f: '＿' }, nani: { a: 'カレー', f: '＿を つくりました' } },
    pic: 'よるの だいどころで、おかあさんが カレーを つくっている', en: 'In the evening, a mother stirs curry in a pot in a kitchen' },
  { id: '2-35', st: 7, t: ['きのうの ことです。', 'けんくんは たいいくかんで ドッジボールを しました。'],
    itsu: 'きのう', doko: 'たいいくかん', dare: 'けんくん', nani: 'ドッジボールを しました',
    q: { nani: 'けんくんは なにを しましたか？' },
    k: { itsu: { a: 'きのう', f: '＿' }, doko: { a: 'たいいくかん', f: '＿' }, dare: { a: 'けん', f: '＿くん' }, nani: { a: 'ドッジボール', f: '＿を しました' } },
    pic: 'たいいくかんで、男の子が ドッジボールを なげている', en: 'A boy throws a ball while playing dodgeball in a school gym' },

  // ── ステージ8：2文（まちがいやすい ことばが 2つ）
  { id: '2-36', st: 8, t: ['あさ、そらくんは いえで パンを たべました。', 'ひるに、こうえんで すなあそびを しました。'],
    itsu: 'ひる', doko: 'こうえん', dare: 'そらくん', nani: 'すなあそびを しました',
    q: { itsu: 'いつ すなあそびを しましたか？', doko: 'どこで すなあそびを しましたか？', dare: 'だれが すなあそびを しましたか？', nani: 'そらくんは ひるに なにを しましたか？' },
    k: { itsu: { a: 'ひる', f: '＿' }, doko: { a: 'こうえん', f: '＿' }, dare: { a: 'そら', f: '＿くん' }, nani: { a: 'すなあそび', f: '＿を しました' } },
    pic: 'こうえんの すなばで、男の子が すなあそびを している', en: 'A boy plays with sand and a bucket in a park sandbox' },
  { id: '2-37', st: 8, t: ['{夕|ゆう}がた、めいさんは {犬|いぬ}と さんぽに いきました。', '{川|かわ}の そばで、{犬|いぬ}が ボールを おいかけました。'],
    itsu: '{夕|ゆう}がた', doko: '{川|かわ}の そば', dare: '{犬|いぬ}', nani: 'ボールを おいかけました',
    q: { itsu: 'いつの ことですか？', doko: 'どこで ボールを おいかけましたか？', dare: 'だれが ボールを おいかけましたか？', nani: '{犬|いぬ}は なにを おいかけましたか？' },
    k: { itsu: { a: 'ゆうがた', f: '＿' }, doko: { a: 'かわ', f: '＿の そば' }, dare: { a: 'いぬ', f: '＿' }, nani: { a: 'ボール', f: '＿を おいかけました' } },
    pic: 'ゆうがたの 川の そばで、犬が ボールを おいかけ、女の子が みている', en: 'At sunset, a dog chases a ball by a river while a girl watches' },
  { id: '2-38', st: 8, t: ['{月|げつ}ようびに、たくみくんは かぜを ひきました。', '{火|か}ようびに、びょういんへ いきました。'],
    itsu: '{火|か}ようび', doko: 'びょういん', dare: 'たくみくん', nani: 'かぜを ひきました',
    q: { itsu: 'いつ びょういんへ いきましたか？', doko: 'たくみくんは {火|か}ようびに どこへ いきましたか？', dare: 'だれが かぜを ひきましたか？', nani: 'たくみくんは {月|げつ}ようびに どう なりましたか？' },
    k: { itsu: { a: 'かようび', f: '＿' }, doko: { a: 'びょういん', f: '＿' }, dare: { a: 'たくみ', f: '＿くん' }, nani: { a: 'ひき', f: 'かぜを ＿ました' } },
    pic: 'へやで、マスクを した 男の子が ねている', en: 'A boy with a cold lies in bed wearing a face mask, thermometer' },
  { id: '2-39', st: 8, t: ['{日|にち}ようびに、おとうさんは いえの まえで {車|くるま}を あらいました。', 'そのあと、まいさんが {車|くるま}を ふきました。'],
    itsu: '{日|にち}ようび', doko: 'いえの まえ', dare: 'まいさん', nani: '{車|くるま}を ふきました',
    q: { itsu: 'いつの ことですか？', doko: 'どこで {車|くるま}を あらいましたか？', dare: 'だれが {車|くるま}を ふきましたか？', nani: 'まいさんは {車|くるま}を どう しましたか？' },
    k: { itsu: { a: 'にちようび', f: '＿' }, doko: { a: 'いえ', f: '＿の まえ' }, dare: { a: 'まい', f: '＿さん' }, nani: { a: 'ふき', f: '{車|くるま}を ＿ました' } },
    pic: 'いえの まえで、女の子が タオルで 車を ふいている。よこに おとうさん', en: 'A girl wipes a car with a towel in front of a house, her father nearby with a hose' },
  { id: '2-40', st: 8, t: ['あさ、にわとりが なきました。', 'その こえで、ねこの タマが へやで めを さましました。'],
    itsu: 'あさ', doko: 'へや', dare: 'タマ', nani: 'めを さましました',
    q: { itsu: 'いつの ことですか？', doko: 'タマは どこで めを さましましたか？', dare: 'だれが めを さましましたか？', nani: 'タマは なにを しましたか？' },
    k: { itsu: { a: 'あさ', f: '＿' }, doko: { a: 'へや', f: '＿' }, dare: { a: 'タマ', f: '＿' }, nani: { a: 'さまし', f: 'めを ＿ました' } },
    pic: 'あさ、へやで、ねこが めを さまして のびを している。まどの そとに にわとり', en: 'In the morning, a cat wakes up and stretches in a room, a rooster crowing outside the window' },

  // ── ステージ9：3文
  { id: '2-41', st: 9, t: ['えんそくの {日|ひ}です。', 'こどもたちは バスに のりました。', 'どうぶつえんで キリンを みました。'],
    itsu: 'えんそくの {日|ひ}', doko: 'どうぶつえん', dare: 'こどもたち', nani: 'キリンを みました',
    q: { itsu: 'いつの ことですか？', doko: 'どこで キリンを みましたか？', dare: 'だれが バスに のりましたか？', nani: 'こどもたちは どうぶつえんで なにを みましたか？' },
    k: { itsu: { a: 'えんそく', f: '＿の ひ' }, doko: { a: 'どうぶつえん', f: '＿' }, dare: { a: 'こども', f: '＿たち' }, nani: { a: 'キリン', f: '＿を みました' } },
    pic: 'どうぶつえんで、こどもたちが キリンを みている', en: 'On a school trip, children look up at a giraffe at a zoo' },
  { id: '2-42', st: 9, t: ['はるの ことです。', 'あおいさんは はたけに いきました。', 'たくさん いちごを つみました。'],
    itsu: 'はる', doko: 'はたけ', dare: 'あおいさん', nani: 'いちごを つみました',
    q: { itsu: 'いつの ことですか？', doko: 'どこに いきましたか？', dare: 'だれが いちごを つみましたか？', nani: 'あおいさんは いちごを どう しましたか？' },
    k: { itsu: { a: 'はる', f: '＿' }, doko: { a: 'はたけ', f: '＿' }, dare: { a: 'あおい', f: '＿さん' }, nani: { a: 'つみ', f: 'いちごを ＿ました' } },
    pic: 'はるの いちごばたけで、女の子が いちごを つんでいる', en: 'In spring, a girl picks strawberries in a strawberry field' },
  { id: '2-43', st: 9, t: ['よる、そとは さむかったです。', 'おじいちゃんは へやで おちゃを のみました。', 'からだが あたたまりました。'],
    itsu: 'よる', doko: 'へや', dare: 'おじいちゃん', nani: 'おちゃを のみました',
    q: { itsu: 'いつの ことですか？', doko: 'どこで おちゃを のみましたか？', dare: 'だれが おちゃを のみましたか？', nani: 'おじいちゃんは へやで なにを しましたか？' },
    k: { itsu: { a: 'よる', f: '＿' }, doko: { a: 'へや', f: '＿' }, dare: { a: 'おじいちゃん', f: '＿' }, nani: { a: 'のみ', f: 'おちゃを ＿ました' } },
    pic: 'よるの へやで、おじいちゃんが あたたかい おちゃを のんでいる', en: 'On a cold night, a grandfather drinks hot green tea in a warm room' },
  { id: '2-44', st: 9, t: ['あきの {日|ひ}、どんぐりが たくさん おちて いました。', 'りすは {森|もり}で どんぐりを ひろいました。', 'ほっぺが まるく ふくらみました。'],
    itsu: 'あき', doko: '{森|もり}', dare: 'りす', nani: 'どんぐりを ひろいました',
    q: { itsu: 'いつの ことですか？', doko: 'どこで どんぐりを ひろいましたか？', dare: 'だれが どんぐりを ひろいましたか？', nani: 'りすは {森|もり}で なにを しましたか？' },
    k: { itsu: { a: 'あき', f: '＿' }, doko: { a: 'もり', f: '＿' }, dare: { a: 'りす', f: '＿' }, nani: { a: 'ひろい', f: 'どんぐりを ＿ました' } },
    pic: 'あきの 森で、ほっぺの ふくらんだ りすが どんぐりを ひろっている', en: 'In an autumn forest, a squirrel with puffy cheeks picks up acorns' },
  { id: '2-45', st: 9, t: ['たんじょうびの ことです。', 'ゆいさんは いえで ケーキを たべました。', 'ろうそくは 7ほん ありました。'],
    itsu: 'たんじょうび', doko: 'いえ', dare: 'ゆいさん', nani: 'ケーキを たべました',
    q: { itsu: 'いつの ことですか？', doko: 'どこで ケーキを たべましたか？', dare: 'だれが ケーキを たべましたか？', nani: 'ゆいさんは いえで なにを たべましたか？' },
    k: { itsu: { a: 'たんじょうび', f: '＿' }, doko: { a: 'いえ', f: '＿' }, dare: { a: 'ゆい', f: '＿さん' }, nani: { a: 'ケーキ', f: '＿を たべました' } },
    pic: 'たんじょうびに、女の子が ろうそくの ついた ケーキを たべている', en: 'A girl celebrates her birthday at home with a cake with seven candles' },

  // ── ステージ10：3文（まちがいやすい ことばが いくつも）
  { id: '2-46', st: 10, t: ['あさ、はるとくんは バスに のりました。', 'ひるに、うみで かにを みつけました。', 'よる、いえで ぐっすり ねました。'],
    itsu: 'ひる', doko: 'うみ', dare: 'はるとくん', nani: 'かにを みつけました',
    q: { itsu: 'いつ かにを みつけましたか？', doko: 'どこで かにを みつけましたか？', dare: 'だれが かにを みつけましたか？', nani: 'はるとくんは うみで なにを みつけましたか？' },
    k: { itsu: { a: 'ひる', f: '＿' }, doko: { a: 'うみ', f: '＿' }, dare: { a: 'はると', f: '＿くん' }, nani: { a: 'かに', f: '＿を みつけました' } },
    pic: 'うみで、男の子が かにを みつけて おどろいている', en: 'A boy finds a little red crab on a beach and is surprised' },
  { id: '2-47', st: 10, t: ['きのう、あいさんと ゆなさんは こうえんで あそびました。', 'あいさんは すなばで やまを つくりました。', 'ゆなさんは てつぼうを しました。'],
    itsu: 'きのう', doko: 'こうえん', dare: 'ゆなさん', nani: 'てつぼうを しました',
    q: { itsu: 'いつの ことですか？', doko: 'ふたりは どこで あそびましたか？', dare: 'だれが てつぼうを しましたか？', nani: 'ゆなさんは なにを しましたか？' },
    k: { itsu: { a: 'きのう', f: '＿' }, doko: { a: 'こうえん', f: '＿' }, dare: { a: 'ゆな', f: '＿さん' }, nani: { a: 'てつぼう', f: '＿を しました' } },
    pic: 'こうえんで、女の子が すなばで やまを つくり、もう 1人の 女の子が てつぼうを している', en: 'Two girls in a park: one builds a sand mound in a sandbox, the other plays on a horizontal bar' },
  { id: '2-48', st: 10, t: ['あさ、{犬|いぬ}の ポチは いえで ねて いました。', 'ひるに、にわへ でました。', 'にわで、ちょうちょを おいかけました。'],
    itsu: 'ひる', doko: 'にわ', dare: 'ポチ', nani: 'ちょうちょを おいかけました',
    q: { itsu: 'いつ にわへ でましたか？', doko: 'どこで ちょうちょを おいかけましたか？', dare: 'だれが ちょうちょを おいかけましたか？', nani: 'ポチは なにを おいかけましたか？' },
    k: { itsu: { a: 'ひる', f: '＿' }, doko: { a: 'にわ', f: '＿' }, dare: { a: 'ポチ', f: '＿' }, nani: { a: 'ちょうちょ', f: '＿を おいかけました' } },
    pic: 'にわで、犬が ちょうちょを おいかけている', en: 'A small dog chases a butterfly in a sunny garden' },
  { id: '2-49', st: 10, t: ['{月|げつ}ようびに、{先生|せんせい}が ひまわりの たねを くばりました。', '{火|か}ようびに、こどもたちは はたけに たねを まきました。', '{水|すい}ようびに、みんなで {水|みず}を やりました。'],
    itsu: '{火|か}ようび', doko: 'はたけ', dare: '{先生|せんせい}', nani: 'たねを まきました',
    q: { itsu: 'いつ たねを まきましたか？', doko: 'どこに たねを まきましたか？', dare: 'だれが たねを くばりましたか？', nani: 'こどもたちは {火|か}ようびに なにを しましたか？' },
    k: { itsu: { a: 'かようび', f: '＿' }, doko: { a: 'はたけ', f: '＿' }, dare: { a: 'せんせい', f: '＿' }, nani: { a: 'まき', f: 'たねを ＿ました' } },
    pic: 'がっこうの はたけで、こどもたちが ひまわりの たねを まいている', en: 'Children plant sunflower seeds in a school garden with their teacher' },
  { id: '2-50', st: 10, t: ['なつ{休|やす}みに、そうまくんは おばあちゃんの いえに いきました。', 'おばあちゃんは スイカを きりました。', 'そうまくんは にわで スイカを たべました。'],
    itsu: 'なつ{休|やす}み', doko: 'にわ', dare: 'おばあちゃん', nani: 'スイカを たべました',
    q: { itsu: 'いつの ことですか？', doko: 'そうまくんは どこで スイカを たべましたか？', dare: 'だれが スイカを きりましたか？', nani: 'そうまくんは にわで なにを たべましたか？' },
    k: { itsu: { a: 'なつやすみ', f: '＿' }, doko: { a: 'にわ', f: '＿' }, dare: { a: 'おばあちゃん', f: '＿' }, nani: { a: 'スイカ', f: '＿を たべました' } },
    pic: 'なつの にわで、男の子が スイカを たべている。よこに おばあちゃん', en: 'In summer, a boy eats a slice of watermelon in a garden, his grandmother beside him' },
];

// レベル1で、選択肢を自動で選ぶときの「にている ことば」のなかま
const POOL = {
  itsu: [
    ['あさ', 'ひる', 'よる', '{夕|ゆう}がた'],
    ['きのう', 'きょう', 'あさ', 'よる'],
    ['はる', 'なつ', 'あき', 'ふゆ'],
    ['{日|にち}ようび', '{土|ど}ようび', '{月|げつ}ようび', '{火|か}ようび', '{水|すい}ようび'],
    ['クリスマス', 'おしょうがつ', 'たんじょうび', 'なつ{休|やす}み', 'ふゆ{休|やす}み'],
    ['{休|やす}みじかん', 'きゅうしょくの あと', 'ほうかご'],
    ['{雨|あめ}の {日|ひ}', 'ゆきの {日|ひ}', 'はれの {日|ひ}'],
    ['えんそくの {日|ひ}', 'うんどうかいの {日|ひ}', 'たんじょうび', 'おしょうがつ'],
  ],
  doko: [
    ['こうえん', 'にわ', 'はたけ', 'うんどうじょう', 'いけ'],
    ['{山|やま}', '{川|かわ}', 'うみ', '{森|もり}'],
    ['へや', 'だいどころ', 'おふろ', 'げんかん', 'いえ'],
    ['きょうしつ', 'としょしつ', 'たいいくかん', 'うんどうじょう'],
    ['スーパー', 'パンや', 'どうぶつえん', 'えき', 'プール', 'びょういん'],
  ],
  dare: [
    ['ゆうとくん', 'さくらさん', 'はるとくん', 'ゆいさん', 'そうたくん', 'みおさん', 'けんたくん', 'あおいさん', 'だいちくん', 'ひなたさん', 'こはるさん', 'りくくん'],
    ['おかあさん', 'おとうさん', 'おばあちゃん', 'おじいちゃん', '{先生|せんせい}'],
    ['こどもたち', '{先生|せんせい}', 'おとうさん', 'おかあさん'],
    ['ねこ', '{犬|いぬ}', 'うさぎ', 'くま', 'パンダ', 'ペンギン', 'かえる', 'ぞう', 'りす'],
  ],
};

module.exports = { L1, L2, POOL };
